<?php

namespace Neoan3\Components;

use Neoan3\Apps\Db;
use Neoan3\Apps\DbException;
use Neoan3\Apps\Ops;
use Neoan3\Frame\Vastn3;
use Neoan3\Model\IndexModel;

/**
 * Class Email
 * Generated by neoan3-cli (vast-n3 package GPL v3)
 * @package Neoan3\Components
 */
class Email extends Vastn3
{
    /**
     * @var array
     */
    private array $vueComponents = ['login'];

    /**
     * init route
     */
    function init()
    {
        $validity = false;
        if ($code = sub(1)) {
            $validity = $this->verify($code);
        }
        $this
            ->hook('main', 'email', ['valid' => $validity])
            ->vueComponents($this->vueComponents)
            ->output();
    }

    /**
     * @param $code
     * @return array|bool|int|mixed
     * @throws DbException
     */
    function verify($code)
    {
        $user = IndexModel::first(Db::easy('user_email.user_id', ['confirm_code' => $code, '^confirm_date']));
        if(!empty($user)){
            Db::ask('user_email', ['confirm_date' => '.'], ['user_id' => '$' . $user['user_id']]);
            return true;
        }
        return false;

    }

    static function loadTemplate($templateName, $params)
    {
        return Ops::embraceFromFile('component/email/templates/' . $templateName . '.html', $params);
    }
}
